version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build-frontend-and-backend:
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: mrahmedelsayed
          password: Ahmed01273290218
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - aws-cli/setup:
          profile-name: cli-user
      - run: node --version
      - run: yarn --version
      - run:
          name: 'Frontend install'
          command: cd frontend && yarn install
      - run:
          name: 'Frontend Build'
          command: cd frontend && yarn build
      - run:
          name: 'Backend install'
          command: cd backend && yarn install
      - run:
          name: 'Backend Build'
          command: cd backend && yarn build



  run-tests:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: cd frontend && yarn test
          name: Run front-end tests
      - run:
          command: cd backend && yarn test
          name: Run back-end tests

  deploy-frontend-and-backend:
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: mrahmedelsayed
          password: Ahmed01273290218
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run:
          name: 'Deploy frontend'
          command: cd frontend && yarn deploy
      - run:
          name: 'Deploy backend'
          command: cd backend && yarn deploy

workflows:
  storefront:
    jobs:
      - build-frontend-and-backend
      - run-tests
      - deploy-frontend-and-backend