version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '14'
      - aws-cli/setup:
          profile-name: cli-user
      - eb/setup
      - run: node --version
      - run: aws --version
      - run: eb --version
      - run:
          name: 'Install Frontend'
          command: npm run frontend:install
      - run:
          name: 'Build Frontend'
          command: npm run frontend:build
      - run:
          name: 'Test Frontend'
          command: npm run frontend:test
      - run:
          name: 'Deploy frontend'
          command: npm run frontend:deploy

      - run:
          name: 'Install Backend'
          command: npm run backend:install
      - run:
          name: 'Build Backend'
          command: npm run backend:build
      - run:
          name: 'Test Backend'
          command: npm run backend:test
      - run:
          name: 'Deploy backend'
          command: npm run backend:deploy


workflows:
  storefront:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

