branch-defaults:
  default:
    environment: Storefront-env
    group_suffix: null
  main:
    environment: Storefront-env
    group_suffix: null
deploy:
  artifact: www.zip
environment-defaults:
  Storefront-env:
    branch: null
    repository: null
global:
  application_name: storefront
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: cli-user
  repository: null
  sc: git
  workspace_type: Application
